[project]
name = "aioqzone-feed"
version = "1.3.2.dev1"
description = "aioqzone plugin that provides higher level apis for processing feeds."
authors = [{ name = "aioqzone" }]
maintainers = [
    { name = "JamzumSum", email = "22952836+JamzumSum@users.noreply.github.com" },
]
license = { text = "AGPL-3.0" }
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["aioqzone>=1.9.6.dev1", "pychaosvm"]

[project.optional-dependencies]
slide-captcha = ["slide-tc~=0.1.3"]

[project.urls]
"Repository" = "https://github.com/aioqzone/aioqzone-feed"
"Documentation" = "https://aioqzone.github.io/aioqzone-feed"
"Bug Tracker" = "https://github.com/aioqzone/aioqzone-feed/issues"

[dependency-groups]
test = ["pytest>=8.2.1", "pytest-asyncio~=1.3.0"]
dev = ["pre-commit", "ruff"]
doc = [
    "Sphinx>=8.1.3; python_version >= '3.10' and python_version < '3.11'",
    "Sphinx~=9.0; python_version >= '3.11'",
    "autodoc-pydantic",
    "sphinx-autodoc-typehints>=1.19",
    "furo",
    "sphinx-intl",
]

[tool.uv.sources]
pychaosvm = { index = "aioqzone-index" }
slide-tc = { index = "aioqzone-index" }

[[tool.uv.index]]
name = "aioqzone-index"
url = "https://aioqzone.github.io/aioqzone-index/simple/"

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

# tool configurations
[tool.pytest.ini_options]
pythonpath = "src"
log_cli = true
log_cli_level = "WARNING"
asyncio_default_fixture_loop_scope = "module"

[tool.ruff]
line-length = 99

[tool.pyright]
pythonVersion = "3.10"
pythonPlatform = "All"
